[build]
root = "video_downloader"

[deploy]
startCommand = """
python manage.py migrate --noinput && 
python manage.py collectstatic --noinput && 
gunicorn video_downloader.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --threads 2 --timeout 0
"""